baseurl = "/"
languageCode = "en-us"
title = "Introducción a la Economía"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
min_version = "0.18"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Bibliografía"
    url = "/bibliografia/"
    weight = 3
[[menu.main]]
    name = "Sobre"
    url = "/sobre/"
    weight = 4


[params]
    description = "El sitio web de Introducción a la Economía"
    footer = "&copy; [Rafael La Buonora](http://www.rlabuonora.com) 2019 | [Github](https://github.com/rlabuonora) | [Twitter](https://twitter.com/rlabuonora)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
