---
title: 'Introducción'
author: ''
date: '2019-03-11'
slug: introduction
categories: []
tags: []
---

# ¿Por qué estudiar economía?

Algunas preguntas que busca responder la economía:

- ¿Por qué algunos países son más ricos que otros?
- ¿Cómo se determina el salario de los trabajadores?
- ¿Qué medidas debe tomar el gobierno para mejorar el bienestar de la población?
- ¿Qué efectos tiene el comercio con otros países?

Las ciencias economómicas aportan conceptos importantes para entender la discusión pública sobre problemas sociales, y para tomar mejores decisiones privadas (¿cómo invertir mis ahorros? ¿qué carrera estudiar?)

- Escasez y eficiencia.
- Macroeconomía y microeconomía.

# Los principales problemas que enfrenta la economía

- **¿Qué producir?**
<p>
Las economías tienen _estructuras productivas_ diferentes. 
</p>
- **¿Cómo producir?**
<p>
Las economías usan _tecnologías_ diferentes.
</p>
- **¿Para quién producir?**
<p>
Las economías _distribuyen_ lo que producen de formas diferentes.
</p>


Los **precios** tienen un rol fundamental en la forma en que una sociedad responde estas preguntas, por lo que la economía busca entender como se determinan.
