---
title: "Economía Abierta"
author: ''
date: '2019-10-21'
slug: economia-abierta
categories: []
tags: []
weight: 14
draft: true
---

## Ejercicios

1. Completar la siguiente tabla:

| Moneda         | Moneda por USD   | USD por Moneda   | 
|----------------|---------     |---------|
|Dólar Canadá    |0.9861        |         |
|Real            |1.656         |         |
|Yuan            |6.942         |         |
|Peso Mexico     |10.38         |         |
|Libra           |0.5054        |         |
|Euro            |0.6368        |         |

2. Explicar el efecto en el tipo de cambio en Uruguay de un aumento de las exportaciones de celulosa.

3. Explicar en cuál sección de la balanza de pagos va cada una de las siguientes transacciones:

  - El Gobierno emite bonos en el exterior
  - La UE aprueba un fondo de cooperación para mejorar la competitividad.
  - UPM repatria beneficios a Finlandia.
  - Un frigorífico exporta un contenedor de carne.
  - Un importador recibe un container de electrodomésticos.
  - Un uruguayo compra acciones de Google con sus ahorros.
  - Un turista argentino se aloja en un hotel uruguayo.
  
4. En un país se registran las siguientes transacciones:
  - Exportaciones de automóviles $100
  - Exportaciones de maíz $150
  - Importaciones de petróleo $150
  - Importaciones de acero $75
  - Viajes al exterior $25
  - Préstamos al extranjero $50
  - Préstamos del extranjero $40
  - Aumento de las reservas del Banco Central $30
  
Calcular la cuenta de errores y omisiones.

5. Leer [este artículo](https://www.180.com.uy/articulo/80359_bcu-busca-que-circulo-virtuoso-de-la-percepcion-de-uruguay-no-haga-caer-el-dolar). Explicar los efectos esperados de las bajas en las tasas de los paìses desarrollados en los flujos de capitales hacia las economías emergentes. Explicar los comentarios de la Unión de Exportadores. Explicar la posición del BCU respecto a intervenir en el mercado de cambios.

6. Leer [este artículo](https://www.180.com.uy/articulo/72878_bergara-reconocio-una-presion-al-atraso-cambiario). Explicar que significa el atraso cambiario. 

7. Explicar este hilo:

```{r echo=FALSE}
blogdown::shortcode('tweet', '1308464967855861761')
```
