---
title: "Los consumidores"
author: Rafael La Buonora
date: '2020-04-30'
slug: utilidad
categories: []
tags: []
weight: 6
---

El princial propósito de la actividad económica es el consumo. En esta unidad analizamos el comportamiento de los consumidores.

- [Diapositivas](https://consumidor--diapos-econ.netlify.app) para estas clases

Ejercicios

1. Considere los siguientes datos para un bien:

| Cantidad   | Utilidad Total  | Utilidad Marginal 
|------------|:---------------:|------------------|
| 0          |   0             |                  |
| 1          |   4             |                  |
| 2          |   7             |                  |
| 3          |   9             |                  | 
| 4          |   10            |                  |
| 5          |   10            |                  |

    a) Grafique la Utilidad Total.
    b) ¿Cuál es la diferencia entre la Utilidad Total y la Utilidad Marginal?
    c) Complete la columna de Utilidad Marginal. 
    d) ¿Tiene rendimientos crecientes o decrecientes?
    
2. Suponga que una familia tiene un ingreso de $100.000 y gasta un tercio en educación, un tercio en vivienda y un tercio en alimentación. Escriba la relación entre la utilidad marginal de cada uno de los tres bienes y el precio de los tres bienes. Si sube el precio de la educación, ¿cómo se debe reasignar el gasto para que esta relación se mantenga?

3. En un mercado hay tres consumidores. El consumidor 1 tiene la  función de demanda $Q_d = 100 - 6P$, el consumidor 2 tiene la demanda $Q_d = 80 - 5P$ y el consumidor 3 $Q_d = 90 - 7P$. Calcular la cantidad demandada de todo el mercado cuando el precio es $5.

4. La demanda para cruzar un peaje es $Q_d = 1000000 - 50000P$, donde $Q_d$ es la cantidad de autos que pasan por el peaje y $P$ es el precio que pagan. Calcular el excedente del consumidor si el precio es $0, $1 y $20.

  