---
title: 'Macroeconomía'
author: ''
date: '2020-07-29'
slug: macroeconomia
categories: []
tags: []
weight: 7
draft: true
---


La Macroeconomía es la rama de la economía que estudia el comportamiento de la economía de una región, un país o el mundo. Busca responder preguntas como:

- ¿Qué tan difícil es encontrar empleo?
- ¿Los salarios y el bienestar material de la población esta mejorando?
- ¿Qué pasa con el nivel de precios y el poder adquisitivo de los ingresos?
- ¿Cómo se comporta el tipo de cambio?

Algunos conceptos importantes:

- __Ciclo de negocios__ La economía pasa por períodos de expansión y contracción del nivel de actividad.

- __Inflación__ El nivel general de precios de la economía puede ser más o menos estable.

- __Crecimiento económico__ En el largo plazo, el bienestar de los habitantes de un país depende de la capacidad de la economía de aumentar la producción de bienes y servicios.

## Objetivos de la política macroeconómica

- __Nivel de actividad__ Alto y creciente. Se mide por el PIB.
- __Nivel de precios__ Estable. La inflación tiene efectos negativos sobre la toma de decisiones y tiene un impacto regresivo en la distribución del ingreso.
- __Desempleo__ Bajo. Es un problema social e implica capacidades productivas inutilizadas. Está muy ligado al ciclo de negocios.

## Instrumentos de la política macroeconómica

### __Política Fiscal__ 
A través de los impuestos, el gobierno afecta los ingresos de los hogares y los precios relativos de algunos bienes (energía, cigarrillos).

A través del __gasto público__ el gobierno afecta los ingresos de los hogares (transferencias) y el acceso a ciertos bienes (salud, educación, seguridad).

- __Política Monetaria__ El gobierno regula la cantidad de dinero circulante en la economía, el crédito y los precios de ciertos clave modificando las tasas de interés y administrando el sistema bancario. 

- __Inserción internacional__ El comercio internacional (exportaciones e importaciones) son clave para las economías pequeñas como Uruguay. Los instrumentos disponibles para incidir en estas variables son los aranceles y las cuotas. Además, las economías tienen relaciones financieras con el exterior. El gobierno regula estas relaciones mediante el sistema cambiario.


# Oferta y Demanda Agregadas

```{r echo = FALSE, warning=FALSE, message=FALSE}
library(tidyverse)

OA <- Hmisc::bezier(
  x=c(1000, 3000, 3200, 3300, 3500, 3700, 3900),
  y=c(100, 150, 155, 160, 170, 180, 250)
) %>% 
  as_tibble


DA <- Hmisc::bezier(
  x=c(1200, 1500, 3000, 3800, 4300),
  y=c(300, 250, 150, 90, 70)
) %>% 
  as_tibble()

ggplot(data.frame(), aes(x, y)) + 
  geom_line(data = OA) +
  geom_line(data = DA) +
  scale_x_continuous(limits =c(0, 5000)) + 
  scale_y_continuous(limits = c(0, 280)) + 
  geom_point(data=tibble(x=3000, y=150)) + 
  annotate("text", x=4500, y=55, label="DA") + 
  annotate("text", x=4000, y=260, label="OA") + 
  labs(y="Nivel de Precios", x="PIB") +
  theme_bw()
```



# Ejercicios

Para calcular la tasa de crecimiento de una variable entre $t-n$ y $t$, usar la fórmula:

$$ g_t = 100 * [(\frac{X_t}{X_{t-n}})^{1/n}-1]$$

1. Calcular la tasa de crecimiento del PIB en términos reales entre 1955 y 1968.

2. Usando los datos del INE, calcular la tasa de inflación entre 1972 y 1992 y entre 1994 y 2012. Comparar los dos períodos y sus efectos sobre el bienestar de la población.

3. Explicar los efectos de los siguientes _shocks_ macroeconómicos:
  a. Una rebaja del IRPF.
  b. Una reducción en el gasto en defensa.
  c. Una avance tecnológico que afecta todos los sectores de producción.
  d. Una rebaja en las tasas de interés.

Graficar los impactos usando el esquema de Oferta y Demanda Agregadas.

4. Se cuenta con los siguientes datos para la economía de EUA:

| Año           | PIB Real      | Nivel de Precios  |
| ------------- |:-------------:| -----:|
| 1981          | 5.291,7       | 59,1 |
| 1982          | 5.189,3       | 62,7 |
| 1983          | 5.423.8       | 65,2 |
| 1984          | 5.8913,6      | 67,6 |

1. Calcular las tasas de inflación y de crecimiento del PIB para cada año.
2. Graficar los 4 años en el eje $(P, Y)$ con las curvas de Oferta y Demanda Agregadas.



# Ejercicios


