---
title: Las empresas
date: '2020-06-23'
slug: las-empresas
weight: 7

---

En esta sección analizamos a los agentes que se encargan de la oferta de los bienes y servicios de la economía. 

Para entender cómo toman decisiones las empresas, es necesario entender las principales variables que toman en cuenta: los ingresos, los costos y los beneficios.

En <a href="https://produccion--diapos-econ.netlify.com">este link </a> están las diapositivas para esta(s) clases.


# Ejercicio 1 

Los costos, los precios de los factores y la cantidad de inputs están vinculados:

| Producción |Tierra  |Trabajadores    |Renta           |Salario |Costo Total|
|------------|--------|----------------|----------------|--------|-----------|
| 0 |10      |0        | 5.5    |5 |
| 1 |10      |6         | 5.5   |5| 
| 2 |10      |11         | 5.5  |5 | 
| 3 |10      |15         | 5.5  |5 |
| 4 |10      |21        | 5.5  |5 |
| 5 |10      |31        | 5.5  |5 |
| 6 |10      |45        | 5.5  |5 |


- Calcular el Costo Total, Costo Fijo y el Costo Medio.

# Ejercicio 2

Leer [esta nota](https://ladiaria.com.uy/articulo/2010/5/salarios-productividad-y-poder/) y contestar las siguientes preguntas:

1) ¿Qué tan extendido está el uso de pago x productividad en la economía Uruguaya?
2) ¿Qué ventajas tiene este sistema? ¿Qué desventajas tiene?
4) Qué dificultades tiene ajustar las remuneraciones x los resultados de las empresas? ¿Qué solución implementaron las economías de la UE a estos problemas?
5) ¿Por qué sugiere el autor que Uruguay está en una posición favorable para experimentar con la reglamentación en estos temas?


