---
title: Las Economías Modernas
author: ''
date: '2019-03-26'
slug: economias-modernas
categories: []
tags: []
weight: 3
---

# Complejidad de las economías modernas

- Ejemplo de una transacción simple como la compra de un pasaje de avión.

- Economías **mixtas**: los recursos se asignan por mecanismos de _mercado_ y directamente por el _estado_.

# El mercado como mecanismo de asignación de recursos

- Un mercado es el marco en el que interactúan los *oferentes* y los *demandantes* de un bien, que son los que deciden cuanto compra y venden a cierto precio con el fin de obtener un resultado (ganancia, satisfacción de necesidades, etc.).
- No hay un individuo o empresa responsable de "hacer funcionar" los mercados. Hay mercados de muchos tipos (centralizados, descentralizados, electrónicos, etc.).
- El rol de los mercados es determinar los **precios** y las **cantidades** que se compran de cada bien en la economía (autos, toneladas de celulosa, clases de economía).
- Estos precios sirven como **señales** para los agentes económicos, y son imprescindibles para **coordinar** su acción.
- El **equilibrio** de mercado es una combinación de precios y cantidades que haya un balance entre oferta y demanda, y que no se produzca de más ni de menos.

- Los mercados son una forma de determinar:
  - ¿Qué producir? Si nadie compra algo, el productor recibe una señal de que no es socialmente deseable destinar recursos a su producción.
  - ¿Cómo producir? Una nueva tecnología de producción será adoptada si aumenta más los ingresos que los costos.
  - ¿Para quién producir? Los ingresos de los miembros de una sociedad se determinan por los precios de los factores productivos que poseen.
  
- Los principales fuerzas que determinan el funcionamiento de la economía: las preferencias y la tecnología.
- Las preferencias son los gustos de los consumidores, y determinan donde nos vamos a parar en la FPP.
- La tecnología determina los límites de lo que podemos producir con los factores productivos que poseemos.
- El flujo circular
- Adam Smith y el descubrimiento del mercado como mecanismo asignador de recursos.

# Tres factores claves en las economías modernas

## Comercio

- El comercio permite la división y la **especialización** de los factores productivos: la tierra, el trabajo y el capital.
- La globalización agrandan el tamaño del mercado y aumentan las posibilidades de división del trabajo de forma que un profesor de economía en Uruguay pueda acceder a bienes producidos en China por una empresa de EUA con mano de obra local.

## Capital

- En las economías modernas el capital -maquinaria, edificios, etc- tiene un rol fundamental para aumentar la productividad de los trabajadores.


## Dinero

- La importancia del dinero para facilitar el intercambio y la especialización. 
- Sin dinero deberíamos usar el trueque, y dependemos de que las personas que producen lo que necesitamos quieran lo que nostros producimos.

# El rol del Estado

En **competencia perfecta**, el mercado asigna los recursos de manera eficiente. Sin embargo, en una economía mixta, el Estado tiene un rol clave para:

- Corregir situaciones en el que el mercado no funciona en competencia perfecta
  - Monopolios
  - Externalidades

- Corregir resultados eficientes pero injustos (distribución del ingreso demasiado desigual)

- Proveer estabilidad macroeconómica
  - Política Fiscal 
  - Política Monetaria


# Ejercicio

1) Analice las siguientes notas de prensa:

 - [Gobierno inicia mayor ronda de Consejos de Salario de la historia](http://www.180.com.uy/articulo/73654_gobierno-inicia-mayor-ronda-de-consejos-de-salario-de-la-historia)
 
 - [Precio de arrendamiento de tierras aumentó por quinto año consecutivo](http://www.180.com.uy/articulo/55791_precio-de-arrendamiento-de-tierras-aumento-por-quinto-ano-consecutivo)
 
 - [Comercio: crecimiento en 2017 y advertencias para un buen 2018](http://www.180.com.uy/articulo/73090_comercio-tuvo-un-2017-de-crecimiento-y-espera-un-buen-2018)
 
 - [Abundancia y precios bajos en frutas y hortalizas en 2017](http://www.180.com.uy/articulo/71800_abundancia-y-precios-bajos-en-frutas-y-hortalizas-en-2017)
 
 Para cada artículo identificar los elementos del flujo circular de la economía mencionados: oferta, demanda, precios, flujos de dinero y de bienes.