---
title: 'Introducción'
author: ''
date: '2020-03-01'
slug: introduction
categories: []
tags: []
weight: 1
---

# ¿Por qué estudiar economía?

Algunas preguntas que busca responder la economía:

- ¿Por qué algunos países son más ricos que otros?
- ¿Cómo se determina el salario de los trabajadores?
- ¿Qué medidas debe tomar el gobierno para mejorar el bienestar de la población?
- ¿Qué efectos tiene el comercio con otros países?

Las ciencias economómicas aportan conceptos importantes para entender la discusión pública sobre problemas sociales, y para tomar mejores decisiones privadas (¿cómo invertir mis ahorros? ¿qué carrera estudiar?)

- Economía normativa y economía positiva.
- Escasez y eficiencia.
- Macroeconomía y microeconomía.


# Los principales problemas que enfrenta la economía

- **¿Qué producir?**
<p>
Las economías tienen _estructuras productivas_ diferentes. 
</p>
- **¿Cómo producir?**
<p>
Las economías usan _tecnologías_ diferentes.
</p>
- **¿Para quién producir?**
<p>
Las economías _distribuyen_ lo que producen de formas diferentes.
</p>


Los **precios** tienen un rol fundamental en la forma en que una sociedad responde estas preguntas, por lo que la economía busca entender como se determinan.

# Ejercicio 1
Determinar si son positivas o normativas. Identificar variables económicas mencionadas.

> Un salario mínimo incrementa el desempleo entre obreros jóvenes no calificados.

> La distribución del ingreso en Uruguay debería ser más equitativa.

> Las leyes antimonopolio deberían utilizarse con más vigor para reducir en nivel actual del poder monopólico.

> El poder de los sindicatos debería restringirse de manera significativa.

> El motivo fundamental del incremento de los precios del petróleo en los últimos 3 años es el poder monopólico de las grandes empresas.

> Un tope en los alquileres reduce la cantidad y la calidad de las viviendas disponibles.

> El ministro de Economía, Danilo Astori, dijo este jueves que el nivel de desempleo en Uruguay,  se ubicó en 7,6% en el segundo trimestre del año. Según el ministro, el desempleo  "no llegó a niveles dramáticos". </br>
Astori también habló de la inflación, que llegó a 9,48% en los 12 meses cerrados a agosto, debido a la suba de precios del mes de casi 1,2%. En ese sentido, dijo que la misma "está asumida como un problema que hay que solucionar".

# Ejercicio 2

De un planeta lejano donde los recursos son infinitos, llega una criatura a la que le tenemos que explicar algunos conceptos económicos. Defina brevemente:

- Economía
- Mercado
- Productividad
- Eficiencia
- Dinero
- Desempleo
- Inflación


# Ejercicio 3

Explicar cómo se determinan, cuánto, cómo y para quién se producen los siguientes bienes y servicios: educación, transporte y hamburguesas.



# Ejercicio 4

1) Analice las siguientes notas de prensa:

 - [Gobierno inicia mayor ronda de Consejos de Salario de la historia](http://www.180.com.uy/articulo/73654_gobierno-inicia-mayor-ronda-de-consejos-de-salario-de-la-historia)
 
 - [Precio de arrendamiento de tierras aumentó por quinto año consecutivo](http://www.180.com.uy/articulo/55791_precio-de-arrendamiento-de-tierras-aumento-por-quinto-ano-consecutivo)
 
 - [Comercio: crecimiento en 2017 y advertencias para un buen 2018](http://www.180.com.uy/articulo/73090_comercio-tuvo-un-2017-de-crecimiento-y-espera-un-buen-2018)
 
 - [Abundancia y precios bajos en frutas y hortalizas en 2017](http://www.180.com.uy/articulo/71800_abundancia-y-precios-bajos-en-frutas-y-hortalizas-en-2017)
 
 Para cada artículo identificar los elementos del flujo circular de la economía mencionados: oferta, demanda, precios, flujos de dinero y de bienes.


