---
title: Demanda y Oferta
author: ''
date: '2020-03-24'
slug: demanda-y-oferta
categories: []
tags: []
weight: 4
---


```{r setup, include = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.height=4, fig.width=6, warning=FALSE, message = FALSE)
library(tidyverse)
library(ggrepel)
library(cowplot)
library(knitr)

theme_set(theme_minimal() + 
            theme(plot.title = element_text(hjust = 0.5)))

```
# Diapositivas

La oferta y la demanda son las herramientas básicas que los economistas usan para analizar los mercados. En esta unidad presentamos estos conceptos y cómo se usan para explicar los resultados que observamos en la vida económica. Acá están las [diapositivas](https://demanda--diapos-econ.netlify.com) para la unidad.


## Ejercicio 1

Explicar porqué estas afirmaciones son falsas:
  - Una helada en uno de los estados productores de café de Brasil va a producir una caída en el precio del café.
  - El proteccionismo de la industria textil en Uruguay hace que los precios internos de los textiles bajen.
  - El aumento en los precios de la educación privada hace que baje la demanda de educación.
  
## Ejercicio 2

Para los siguientes casos, explicar si cambia la cantidad demandada o la demanda, dibujando un diagrama:
  - El aumento en el gasto militar hace que los uniformes suban de precios.
  - El precio del pescado bajó porque el Papa autorizó a los católicos a comer carne los viernes.
  - Un aumento en los impuestos a la nafta hace que el consumo de nafta baje.
  - Los salarios aumentaron luego de la llegada de la Peste Bubónica a Europa en el Siglo XIV.
  
## Ejercicio 3

Analizar las noticias sobre los mercados de:

- [Yerba](https://www.infobae.com/2013/09/22/1510682-para-mujica-el-aumento-precio-la-yerba-mate-es-una-catastrofe/)
- [Morrón](https://www.telenoche.com.uy/nacionales/el%C2%A0precio-del-morron-rojo-llego%C2%A0-350-pesos-el-kilo)
- [Alcohol en gel](https://www.descuento.uy/abuso-alcohol-en-gel-ya-se-vende-entre-600-y-980-el-litro/)
  
## Ejercicio 4

Tenemos la siguiente información sobre el mercado de pizzas

Precio | Cantidad demandada  | Cantidad Ofrecida
-------| ------------------- |-------------
10     | 0                   | 40
8      | 10                  | 30
6      | 20                  | 20
4      | 30                  | 10
2      | 40                  | 0 
0      | 125                 | 0

1) Graficar la oferta y la demanda. Encontrar el punto de equilibrio del mercado. 
2) Si la demanda de Pizza se triplicara para todos los precios: ¿Qué pasaría si el precio inicial fuera de $4 por pizza?



## Ejercicio 5

¿Cuál de los dos bienes tiene la demanda más elástica?
  - Perfume o sal.
  - Penicilina o helado.
  - Helado o helado de chocolate.

## Ejercicio 6

Completar las siguientes oraciones:
  - Si el precio de un bien sube 1% y la cantidad demandada 0.5%, la demanda es ___________.
  - Si el precio de un bien sube 1% y la cantidad demandada 2%, la demanda es ___________.

## Ejercicio 7

En el mercado de un bien, la demanda es $Q_d = 100 - 6P$ y la oferta $Q_s = 28 + 3P$. Encontrar el equilibrio del mercado y graficarlo.


## Ejercicio 8

Completar la siguiente tabla:

| P   | Q        | Elasticidad  |
|-----|:--------:|:------------:|
| 5   |   9      | -            |
| 4   |   10     |              |
| 3   |   12     |              |
| 2   |   15     |              | 
| 1   |   20     |              |

## Ejercicio 9

Analice los siguientes artículos de prensa y explique a qué se deben las colas en los supermercados en Venezuela usando el modelo de precios mínimos.

  - [La verdadera dimensión de la escasez en Venezuela](https://www.bbc.com/mundo/noticias/2015/05/150512_venezuela_escasez_reportaje_dp)
  - [¿Por qué hay que hacer tanta fila en Venezuela?](https://www.bbc.com/mundo/noticias/2014/02/140203_venezuela_colas_escasez_dp)
